# Generated by Django 6.0.7 on 2026-07-12 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('needs_ocr', 'Needs OCR (scanned PDF)'), ('low_confidence', 'Low Confidence'), ('no_text', 'No Text Detected'), ('unsupported', 'Unsupported File Type'), ('error', 'Extraction Error')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='ocr_confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
