# Generated by Django 6.0.2 on 2026-07-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_medicalreport_ai_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='active_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
