# Generated by Django 6.0.2 on 2026-04-12 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_patient_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('xray', 'X-Ray'), ('blood_test', 'Blood Test'), ('scan', 'Scan'), ('other', 'Other')], max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='medical_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
            ],
        ),
    ]
