# Generated by Django 6.0.2 on 2026-07-04 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emergency', '0002_accesstoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessToken',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
